api.employeePFComparing.tag=employeePFComparing
api.employeePFComparing.description=Employee PF Comparing
api.registerEmployeeForPF.tag=registerEmployeeForPF
api.registerEmployeeForPF.description=Register Employee for PF
api.addSingleEmployeeForPF.tag=addSingleEmployeeForPF
api.addSingleEmployeeForPF.description=Add Single Employee for PF
api.getEmployeePF.tag=getEmployeePF
api.getEmployeePF.description=Get Employee PF
api.getPFForMonthAndYear.tag=getPFForMonthAndYear
api.getPFForMonthAndYear.description=Get PF for Month and Year
api.getEmployeeAccountsById.tag=getEmployeeAccountsById
api.getEmployeeAccountsById.description=Get Employee Accounts by Id
api.updateEmployeeForPf.tag=updateEmployeeForPf
api.updateEmployeeForPf.description=Update Employee for PF
api.deleteEmployeeAccountDetails.tag=deleteEmployeeAccountDetails
api.deleteEmployeeAccountDetails.description=Delete Employee Account Details
api.employeePTComparing.tag=employeePTComparing
api.employeePTComparing.description=Employee Professional Tax Comparing
api.registerEmployeeForPT.tag=registerEmployeeForPT
api.registerEmployeeForPT.description=Register Employee for PT
api.updateEmployeeForPT.tag=updateEmployeeForPT
api.updateEmployeeForPT.description=Update Employee for PT
api.deletePFResponseById.tag=deletePFResponseById
api.deletePFResponseById.description=Delete PF Response by Id
api.updatePFResponse.tag=updatePFResponse
api.updatePFResponse.description=Update PF Response
api.getPFResponse.tag=getPFResponse
api.getPFResponse.description=Get PF Response
api.getPFResponseById.tag=getPFResponseById
api.getPFResponseById.description=Get PF Response by Id
api.addPFResponse.tag=addPFResponse
api.addPFResponse.description=Add PF Response
api.gstComparing.tag=gstComparing
api.gstComparing.description=GST Comparing
api.registerGSTAccount.tag=registerGSTAccount
api.registerGSTAccount.description=Register GST Account
api.addSingleGSTAccount.tag=addSingleGSTAccount
api.addSingleGSTAccount.description=Add Single GST Account
api.getGSTAccountById.tag=getGSTAccountById
api.getGSTAccountById.description=Get GST Account by Id
api.getGSTAccounts.tag=getGSTAccountsByYearAndMonth
api.getGSTAccounts.description=Get GST Accounts by Year and Month
api.getGSTAccountsByCustomer.tag=getGSTAccountsByCustomer
api.getGSTAccountsByCustomer.description=Get GST Accounts by Customer
api.updateGSTAccount.tag=updateGSTAccount
api.updateGSTAccount.description=Update GST Account
api.deleteGSTAccount.tag=deleteGSTAccount
api.deleteGSTAccount.description=Delete GST Account
api.addPTResponse.tag=addPTResponse
api.addPTResponse.description=Add PT Response
api.getPTResponseById.tag=getPTResponseById
api.getPTResponseById.description=Get PT Response by ID
api.getPTResponse.tag=getPTResponse
api.getPTResponse.description=Get PT response
api.updatePTResponse.tag=updatePTResponse
api.updatePTResponse.description=Update PT Response by ID
api.deletePTResponseById.tag=deletePTResponse
api.deletePTResponseById.description=Delete PT Response by ID
api.addTDSResponse.tag=addTDSResponse
api.addTDSResponse.description=Add TDS Response
api.getTDSResponseById.tag=getTDSResponseById
api.getTDSResponseById.description=Get TDS Response by Id
api.getTDSResponse.tag=getTDSResponse
api.getTDSResponse.description=Get TDS Response
api.updateTDSResponse.tag=updateTDSResponse
api.updateTDSResponse.description=Update TDS Response
api.deleteTDSResponseById.tag=deleteTDSResponseById
api.deleteTDSResponseById.description=Delete TDS Response by Id
api.deletePFReceiptById.tag=deletePFReceiptById
api.deletePFReceiptById.description=Delete PF Receipt by Id
api.updatePFReceipt.tag=updatePFReceipt
api.updatePFReceipt.description=Update PF Receipt
api.getPfReceipts.tag=getPfReceipts
api.getPfReceipts.description=Get PF Receipts
api.getPfReceiptsById.tag=getPfReceiptsById
api.getPfReceiptsById.description=Get PF Receipts by Id
api.addPFReceipts.tag=addPFReceipts
api.addPFReceipts.description=Add PF Receipts
api.deletePTReceiptById.tag=deletePTReceiptById
api.deletePTReceiptById.description=Delete PT Receipt by Id
api.updatePTReceipt.tag=updatePTReceipt
api.updatePTReceipt.description=Update PT Receipt
api.getPTReceipts.tag=getPTReceipts
api.getPTReceipts.description=Get PT Receipts
api.getPTReceiptsById.tag=getPTReceiptsById
api.getPTReceiptsById.description=Get PT Receipts by Id
api.addPTReceipts.tag=addPTReceipts
api.addPTReceipts.description=Add PT Receipts
api.addPTReceiptsPayload.description=Add Professional Tax Receipts Payload
api.deleteGSTResponseById.tag=deleteGSTResponseById
api.deleteGSTResponseById.description=Delete GST Response by Id
api.updateGSTResponse.tag=updateGSTResponse
api.updateGSTResponse.description=Update GST Response
api.getGSTResponse.tag=getGSTResponse
api.getGSTResponse.description=Get GST Response
api.getGSTResponseById.tag=getGSTResponseById
api.getGSTResponseById.description=Get GST Response by Id
api.addGSTResponse.tag=addGSTResponse
api.addGSTResponse.description=Add GST Response
api.employeeTDSComparing.tag=employeeTDSComparing
api.employeeTDSComparing.description=Employee TDS Comparing
api.registerEmployeeForTDS.tag=registerEmployeeForTDS
api.registerEmployeeForTDS.description=Register Employee for TDS
api.updateEmployeeForTDS.tag=updateEmployeeForTDS
api.updateEmployeeForTDS.description=Update Employee for TDS
api.getEmployeeTDS.tag=getEmployeeTDS
api.getEmployeeTDS.description=Get Employee TDS
