api.employeePFComparing.tag=employeePFComparing
api.employeePFComparing.description=Employee PF Comparing
api.registerEmployeeForPF.tag=registerEmployeeForPF
api.registerEmployeeForPF.description=Register Employee for PF
api.addSingleEmployeeForPF.tag=addSingleEmployeeForPF
api.addSingleEmployeeForPF.description=Add Single Employee for PF
api.getEmployeePF.tag=getEmployeePF
api.getEmployeePF.description=Get Employee PF
api.getPFForMonthAndYear.tag=getPFForMonthAndYear
api.getPFForMonthAndYear.description=Get PF for Month and Year
api.getEmployeeAccountsById.tag=getEmployeeAccountsById
api.getEmployeeAccountsById.description=Get Employee Accounts by Id
api.updateEmployeeForPf.tag=updateEmployeeForPf
api.updateEmployeeForPf.description=Update Employee for PF
api.deleteEmployeeAccountDetails.tag=deleteEmployeeAccountDetails
api.deleteEmployeeAccountDetails.description=Delete Employee Account Details
api.employeePTComparing.tag=employeePTComparing
api.employeePTComparing.description=Employee Professional Tax Comparing
api.registerEmployeeForPT.tag=registerEmployeeForPT
api.registerEmployeeForPT.description=Register Employee for PT
api.updateEmployeeForPT.tag=updateEmployeeForPT
api.updateEmployeeForPT.description=Update Employee for PT
api.deletePFResponseById.tag=deletePFResponseById
api.deletePFResponseById.description=Delete PF Response by Id
api.updatePFResponse.tag=updatePFResponse
api.updatePFResponse.description=Update PF Response
api.getPFResponse.tag=getPFResponse
api.getPFResponse.description=Get PF Response
api.getPFResponseById.tag=getPFResponseById
api.getPFResponseById.description=Get PF Response by Id
api.addPFResponse.tag=addPFResponse
api.addPFResponse.description=Add PF Response
api.addTDSResponse.tag=addTDSResponse
api.addTDSResponse.description=Add TDS Response
api.getTDSResponseById.tag=getTDSResponseById
api.getTDSResponseById.description=Get TDS Response by Id
api.getTDSResponse.tag=getTDSResponse
api.getTDSResponse.description=Get TDS Response
api.updateTDSResponse.tag=updateTDSResponse
api.updateTDSResponse.description=Update TDS Response
api.deleteTDSResponseById.tag=deleteTDSResponseById
api.deleteTDSResponseById.description=Delete TDS Response by Id
api.deletePFReceiptById.tag=deletePFReceiptById
api.deletePFReceiptById.description=Delete PF Receipt by Id
api.updatePFReceipt.tag=updatePFReceipt
api.updatePFReceipt.description=Update PF Receipt
api.getPfReceipts.tag=getPfReceipts
api.getPfReceipts.description=Get PF Receipts
api.getPfReceiptsById.tag=getPfReceiptsById
api.getPfReceiptsById.description=Get PF Receipts by Id
api.addPFReceipts.tag=addPFReceipts
api.addPFReceipts.description=Add PF Receipts
api.deletePTReceiptById.tag=deletePTReceiptById
api.deletePTReceiptById.description=Delete PT Receipt by Id
api.updatePTReceipt.tag=updatePTReceipt
api.updatePTReceipt.description=Update PT Receipt
api.getPTReceipts.tag=getPTReceipts
api.getPTReceipts.description=Get PT Receipts
api.getPTReceiptsById.tag=getPTReceiptsById
api.getPTReceiptsById.description=Get PT Receipts by Id
api.addPTReceipts.tag=addPTReceipts
api.addPTReceipts.description=Add PT Receipts
api.addPTReceiptsPayload.description=Add Professional Tax Receipts Payload