api.employeePFComparing.tag=employeePFComparing
api.employeePFComparing.description=Employee PF Comparing
api.registerEmployeeForPF.tag=registerEmployeeForPF
api.registerEmployeeForPF.description=Register Employee for PF
api.addSingleEmployeeForPF.tag=addSingleEmployeeForPF
api.addSingleEmployeeForPF.description=Add Single Employee for PF
api.getEmployeePF.tag=getEmployeePF
api.getEmployeePF.description=Get Employee PF
api.getPFForMonthAndYear.tag=getPFForMonthAndYear
api.getPFForMonthAndYear.description=Get PF for Month and Year
api.getEmployeeAccountsById.tag=getEmployeeAccountsById
api.getEmployeeAccountsById.description=Get Employee Accounts by Id
api.updateEmployeeForPf.tag=updateEmployeeForPf
api.updateEmployeeForPf.description=Update Employee for PF
api.deleteEmployeeAccountDetails.tag=deleteEmployeeAccountDetails
api.deleteEmployeeAccountDetails.description=Delete Employee Account Details
api.deletePFResponseById.tag=deletePFResponseById
api.deletePFResponseById.description=Delete PF Response by Id
api.updatePFResponse.tag=updatePFResponse
api.updatePFResponse.description=Update PF Response
api.getPFResponse.tag=getPFResponse
api.getPFResponse.description=Get PF Response
api.getPFResponseById.tag=getPFResponseById
api.getPFResponseById.description=Get PF Response by Id
api.addPFResponse.tag=addPFResponse
api.addPFResponse.description=Add PF Response
api.gstComparing.tag=gstComparing
api.gstComparing.description=GST Comparing
api.registerGSTAccount.tag=registerGSTAccount
api.registerGSTAccount.description=Register GST Account
api.addSingleGSTAccount.tag=addSingleGSTAccount
api.addSingleGSTAccount.description=Add Single GST Account
api.getGSTAccountById.tag=getGSTAccountById
api.getGSTAccountById.description=Get GST Account by Id
api.getGSTAccounts.tag=getGSTAccountsByYearAndMonth
api.getGSTAccounts.description=Get GST Accounts by Year and Month
api.getGSTAccountsByCustomer.tag=getGSTAccountsByCustomer
api.getGSTAccountsByCustomer.description=Get GST Accounts by Customer
api.updateGSTAccount.tag=updateGSTAccount
api.updateGSTAccount.description=Update GST Account
api.deleteGSTAccount.tag=deleteGSTAccount
api.deleteGSTAccount.description=Delete GST Account